### ISSUE TITLE
Better support for compilers where Function.prototype.toString throws a SyntaxError on eval().

### ISSUE THREAD

**Issue by cheako** [humbletim/glm-js#10]
https://github.com/cheako/cheako-vulkan/blob/5fe88eabd4d742bc6554621a8509e2acb78ce2d2/015test.diff

I found out it was 2696, using duktape.  I've opened a bug with them about not providing a stack trace in that instance, but it wouldn't hurt to have these evals protected by try/catch.

**Comment by cheako** [comment]
https://github.com/svaarala/duktape/blob/d33967315cf7efe4c0688c6be51f9792c99db20b/src-input/duk_bi_function.c#L101
Looks like toString on a function need not compile.

**Comment by cheako** [comment]
I patched this up a little,but then I got to line number [1]2839 and saw what A big chore replacing all of these would be.  I had planned to replace the toString function in each of the functions that were passed to deNify.

1. https://pastebin.com/Fpzpq7QE
2. https://pastebin.com/iSaRE23E
```
@@ -5049,7 +5102,7 @@
         return e
     };
     (function() {
-        var a = GLM.$template.deNify({
+        var cheako = {
                 "$vvec<N>": function() {
                     return GLM.$make_componentized_vector("$vvecN", GLM.vecN)
                 },
@@ -5062,7 +5115,20 @@
                 $vquat: function() {
                     return GLM.$make_componentized_vector("$vquat", GLM.quat)
                 }
-            }, "$v"),
+        };
+        cheako["$vvec<N>"].toString = function cheako_vvec_toString() {
+            return 'function() { return GLM.$make_componentized_vector("$vvecN", GLM.vecN) }';
+        };
+        cheako["$vuvec<N>"].toString = function cheako_vvec_toString() {
+            return 'function() { return GLM.$make_componentized_vector("$vuvecN", GLM.uvecN) }';
+        };
+        cheako["$vmat<N>"].toString = function cheako_vvec_toString() {
+            return 'function() { return GLM.$make_componentized_vector("$vmatN", GLM.matN) }';
+        };
+        cheako.$vquat.toString = function cheako_vvec_toString() {
+            return 'function() { return GLM.$make_componentized_vector("$vquat", GLM.quat) }';
+        };
+        var a = GLM.$template.deNify(cheako, "$v"),
             b;
         for (b in a) GLM[b] = a[b]()
     })();
```

**Comment by humbletim** [comment]
Another strategy I've been thinking about is to refactor the code generation out so that it can all take place upfront as part of a static build step.

In theory that would eliminate runtime dependency on `Function.prototype.toString()`.

Do you think that approach would also help solve for your use case?

**Comment by cheako** [comment]
While I was looking at glm-js I came to the same conclusion, code generation could be done prior to minification.  Yes, duktape specifically does not support Function.prototype.toString().  There is only discussion about adding this as a feature, however there is not going to be any(or much) alteration of the original source.  So you might get away with using a String instead of a Function as the argument u pass.

Also I'm building emscripten and was going to try and build glm with it as another potential solution.

**Comment by cheako** [comment]
I finally got cglm to compile as javascript, but looking at the result I don't think it's usable.  U would need to call _malloc() with the correct size for the struct u are trying to create and it would just be a pain for anyone trying to use it.

**Comment by cheako** [comment]
https://github.com/recp/cglm/issues/52
Here is my result, but I think it's far from usable.
https://pastebin.com/Wp4UYiVr
kripken/emscripten#6512

**Comment by cheako** [comment]
There is now pull request https://github.com/humbletim/glm-js/pull/12 so there isn't much need for this issue.
