### ISSUE TITLE
dvec & dmat data types

### ISSUE THREAD

**Issue by vajpeters** [humbletim/glm-js#13]
For more precision calculation it would be nice to have access to dvec and dmat datatypes.

**Comment by humbletim** [comment]
I really appreciate the suggestion for including `dvec` and `dmat` for more precision calculations! As the project is currently being sunset (#19), I am closing out unresolved issues. While implementing this is not feasible now, it's definitely an interesting avenue to explore for future JavaScript libraries. Thank you again for your valuable suggestion and support! -Tim
