### ISSUE TITLE
Errors being thrown in IE11

### ISSUE THREAD

**Issue by jmona789** [humbletim/glm-js#14]
Using the library on a page in IE11 and the following errors are showing int he dev console:
```
'glm_vec3_Error' is undefined
```
Also If I type our glm in the console. it is showing as null, in other browsers it shows the full glm object.
Typing `GLM` in the console in IE11 shows an object but it does not have the function vec3() that I need.  
<img width="982" alt="Screen Shot 2019-05-28 at 11 48 25 AM" src="https://user-images.githubusercontent.com/13789757/58492268-8c1a4c80-813e-11e9-94d0-34b4e7057a1a.png">

**Comment by humbletim** [comment]
Hi Jimmy,

I apologize for the long silence on your issue report (May 2019!). The glm-js project is now undergoing sunsetting (see #19), so I'm closing unresolved issues.

I still wanted to express my gratitude for you taking the time to report the issue and share a screenshot. It was incredibly considerate of you!

While I can't offer a direct solution, I hope you've found other tools or solutions in the meantime.

Best regards, -Tim
