### ISSUE TITLE
extremely slow. Possibly I'm using it wrong

### ISSUE THREAD

**Issue by greggman** [humbletim/glm-js#15]
I might be using this wrong but I just found out about it today and so added to these benchmarks

http://greggman.github.io/webgl-matrix-benchmarks/matrix_benchmark.html?tests=glmatrix,twgl,glm-js,glm-js-gl-matrix

Also it's possible rotate is buggy. I benchmark both glm-js and glm-gl-matrix. They're exactly the same except for which library is included but glm-js returns different results for rotate then glm-gl-matrix

The code to test glm-js is here

https://github.com/greggman/webgl-matrix-benchmarks/blob/master/libs/glm-js/glm-js.html

**Comment by humbletim** [comment]
Interesting -- thanks for including! :)

At first blush it looks like you are using glm-js correctly.

Looking at the Chrome performance profile the biggest culprit seems related to creating multiple mat4 instances each pass, which is as fair of a performance test as any I suppose.  However, normally in tight loops I would think to cache the instances between iterations and use inplace modifiers like `m1['*='](m2)`.

Even though glm-js is likely to be slower than working with a library closer to the metal, I am still surprised to see it performing _that_ much slower and will have to take a deeper look at that and the rotation quirk.

**Comment by ArcaneEngineer** [comment]
> Even though glm-js is likely to be slower than working with a library closer to the metal

This is an interesting one: Why *isn't* glm-js simply cannibalising other libraries for best-performance approaches, and implementing them directly? Wrapper approaches are always going to be slower, and function indirection / JMPs tend to matter in this context.

**Comment by humbletim** [comment]
Hi @ArcaneEngineer -- thanks for the question and thoughts. And yeah.. if I could go back in time I'd probably try exactly what you suggest -- or maybe even attempt to write a program to evaluate routines and cherry-pick top performers into a best-of compilation.

For what it's worth a lot of my thinking with glm-js was more towards durability than speed -- like I wanted to be able to find and apply tricky math solutions without going through an error-proned hand-porting process across math styles.  Like, to the casual observer, a correct math solution written in GLM C++ might not even be recognizable next to its nearest equivalent solution expressed as Three.JS math -- but with glm-js, an idea was that the two counterparts could both be -- and appear to be -- the same one math solution. Or so the theory goes. :)

**Comment by humbletim** [comment]
Thanks for the feedback and discussion. As the project is being sunset (#19), I am closing unresolved issues. Best regards, -Tim
