### ISSUE TITLE
Is the project dead?

### ISSUE THREAD

**Issue by xrui94** [humbletim/glm-js#16]
Last push date is 5 years ago! Is the project dead?

**Comment by davidson16807** [comment]
Does it need to be active? The project has a well defined goal, to implement the glsl standard in javascript. It's done that. Has there been an oversight in the implementation, or has there been an update to the glsl standard?

**Comment by humbletim** [comment]
Good catch! Project sunsetting is underway (see #19 for details), but your math is still sharp two years later. Thanks for checking in!
