### ISSUE TITLE
Incomplete matrix swizzle

### ISSUE THREAD

**Issue by Beuc** [humbletim/glm-js#3]
Hi,

I noticed that the matrix swizzle is incomplete.
For instance I wanted to use .xyw, which is missing, when converting a 3D transformation matrix to a 2D one.
```
    var mvp = ...
    var mvp2D = glm.mat3(mvp[0].xyw, mvp[1].xyw, mvp[3].xyw);
```

I had to manually expand it (see https://gitlab.com/wikibooks-opengl/modern-tutorials/blob/master/2d-webgl/sprites.html).

**Comment by humbletim** [comment]
addressed with #8
